In [1]:
import pandas as pd

data = pd.read_csv('data/MMI_2021-11-11.csv')

data.head()

         Date   Market Mood Index   Nifty Index
0  10/11/2021           38.926312      18017.20
1  09/11/2021           39.661079      18044.25
2  08/11/2021           31.190007      18068.55
3  03/11/2021           26.873659      17829.20
4  03/11/2021           27.878095      17829.20

In [2]:
data.columns

Index(['Date', ' Market Mood Index', ' Nifty Index'], dtype='object')

In [3]:
data[ (data[' Market Mood Index'] < 30 ) | (data[' Market Mood Index'] > 70)][0:50]

           Date   Market Mood Index   Nifty Index
3    03/11/2021           26.873659      17829.20
4    03/11/2021           27.878095      17829.20
6    01/11/2021           28.260705      17929.65
7    29/10/2021           24.068053      17671.65
44   07/09/2021           70.404387      17362.10
45   06/09/2021           71.021354      17377.80
46   03/09/2021           72.223849      17323.60
47   02/09/2021           70.141679      17234.15
93   28/06/2021           70.804587      15814.70
101  16/06/2021           72.887116      15767.55
102  15/06/2021           76.456668      15869.25
103  14/06/2021           74.193287      15811.85
104  11/06/2021           76.346497      15799.35
105  10/06/2021           76.734798      15737.75
106  09/06/2021           76.252473      15635.35
107  08/06/2021           83.745642      15740.10
108  07/06/2021           88.179330      15751.65
109  04/06/2021           86.939494      15670.25
110  03/06/2021           87.737665      15690.35
111  02/06/2021           83.570876      15576.20
112  01/06/2021           80.549021      15574.85
113  31/05/2021           82.215286      15582.80
114  28/05/2021           77.837994      15435.65
115  27/05/2021           70.380822      15337.85
117  25/05/2021           71.842226      15208.45
118  24/05/2021           71.040464      15197.70
140  22/04/2021           28.343702      14406.15
141  20/04/2021           24.656281      14296.40
145  13/04/2021           28.800209      14504.80
146  12/04/2021           27.871048      14310.80
155  26/03/2021           23.091209      14507.30
156  25/03/2021           13.904135      14324.90
157  24/03/2021           26.579029      14549.40
158  23/03/2021           29.694040      14814.75
159  22/03/2021           23.176990      14736.40
160  19/03/2021           29.563294      14744.00
166  09/03/2021           26.988272      15098.40
167  08/03/2021           24.130123      14956.20
168  05/03/2021           18.143137      14938.10
172  01/03/2021           26.712630      14761.55
175  24/02/2021           29.388145      14836.70
176  23/02/2021           24.890782      14707.80
177  22/02/2021           25.922582      14675.70
192  01/02/2021           26.731168      14281.20
193  29/01/2021           21.422240      13634.60
194  28/01/2021           22.555721      13817.55
195  27/01/2021           24.440208      13967.50
196  25/01/2021           26.655001      14238.90
210  05/01/2021           71.572368      14199.50
211  04/01/2021           76.339715      14132.90