<a href="https://colab.research.google.com/github/ankit-rathi/Data-Science-with-Python/blob/master/Stock_Analysis/Nifty100_Performance_Over_Time.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
'''
portfolio = ['alkylamine','asianpaint','axisbank','bergepaint','bhartiartl','canbk','dmart','federalbnk','havells','hdfcbank',
             'hdfclife','hindunilvr','ibrealest','icicibank','indusindbk','infy','irctc','itc','mhril','motilalofs',
             'nationalum','ntpc','paras','reliance','sail','tataconsum','tatamotors','tatapower','tatasteel','tcs','zeel']

nextbuy = ['sbin','titan','ultracemco','kotakbank']

watchlist = ['equitasbnk','hcltech','hdfcamc','heromotoco','iex','infobean','jublfood','lti','tipsindltd',
             'mastek','mindtree','relaxo']

skipped = ['paras']

stock_ids = list(set(portfolio + nextbuy + watchlist) - set(skipped))
'''

"\nportfolio = ['alkylamine','asianpaint','axisbank','bergepaint','bhartiartl','canbk','dmart','federalbnk','havells','hdfcbank',\n             'hdfclife','hindunilvr','ibrealest','icicibank','indusindbk','infy','irctc','itc','mhril','motilalofs',\n             'nationalum','ntpc','paras','reliance','sail','tataconsum','tatamotors','tatapower','tatasteel','tcs','zeel']\n\nnextbuy = ['sbin','titan','ultracemco','kotakbank']\n\nwatchlist = ['equitasbnk','hcltech','hdfcamc','heromotoco','iex','infobean','jublfood','lti','tipsindltd',\n             'mastek','mindtree','relaxo']\n\nskipped = ['paras']\n\nstock_ids = list(set(portfolio + nextbuy + watchlist) - set(skipped))\n"

In [ ]:
import pandas as pd
import numpy as np

mypf = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Data-Science-with-Python/master/Stock_Analysis/data/Nifty100Scrips.csv')

mypf = mypf[mypf['InScope'] == 1]

stock_n100 = mypf['Symbol'].unique()

exclude = ['CADILAHC','MMTC']

stock_n100 = mypf[~mypf['Symbol'].isin(exclude) ]['Symbol']

#stock_ids

stock_ids = stock_n100

In [ ]:
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import pandas_datareader.data as web
import yfinance as yfin
yfin.pdr_override()

start_date = (datetime.date.today() + datetime.timedelta(days=-5)).strftime('%Y-%m-%d')
end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')

df_perform = pd.DataFrame()

for stock_id in stock_ids:
    stock_id = stock_id.upper() + '.NS'
    tmp = pd.DataFrame(web.DataReader(tickers = stock_id, data_source='yahoo', start = start_date, end = end_date))
    tmp['Stock'] = stock_id
    tmp['Prev_Close'] = tmp['Close'].shift(1)
    tmp['Change%'] = round((tmp['Close'] - tmp['Prev_Close'])*100/tmp['Prev_Close'],2)
    tmp = tmp.tail(1)
    df_perform = df_perform.append(tmp)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

In [ ]:
# losers
df_perform.sort_values(by = 'Change%')

,Open,High,Low,Close,Adj Close,Volume,Stock,Prev_Close,Change%
Date,,,,,,,,,
2022-01-14,4630.000000,4675.000000,4477.350098,4507.600098,4507.600098,1391541,MINDTREE.NS,4744.100098,-4.99
2022-01-14,734.799988,735.950012,716.049988,717.950012,717.950012,8815753,AXISBANK.NS,740.700012,-3.07
2022-01-14,3462.000000,3462.000000,3356.199951,3362.199951,3362.199951,529019,ASIANPAINT.NS,3456.250000,-2.72
2022-01-14,919.099976,926.650024,913.250000,916.700012,916.700012,1096633,INDUSINDBK.NS,941.549988,-2.64
2022-01-14,1320.000000,1320.949951,1293.000000,1302.900024,1302.900024,2065300,HCLTECH.NS,1334.250000,-2.35
2022-01-14,821.000000,822.000000,813.000000,813.000000,813.000000,2715408,ICICIBANK.NS,824.700012,-1.42
2022-01-14,5570.000000,5570.000000,5499.950195,5517.149902,5517.149902,82632,NAUKRI.NS,5590.799805,-1.32
2022-01-14,2420.000000,2421.000000,2383.199951,2386.000000,2386.000000,464289,HINDUNILVR.NS,2414.199951,-1.17
2022-01-14,959.000000,959.000000,946.900024,949.299988,949.299988,32006,MOTILALOFS.NS,958.700012,-0.98
2022-01-14,3782.000000,3782.149902,3720.000000,3721.850098,3721.850098,12506,ALKYLAMINE.NS,3758.750000,-0.98
2022-01-14,729.950012,730.900024,724.000000,724.750000,724.750000,1874921,BHARTIARTL.NS,731.799988,-0.96
2022-01-14,783.000000,784.849976,773.900024,774.799988,774.799988,86535,BERGEPAINT.NS,781.950012,-0.91
2022-01-14,100.449997,101.000000,99.000000,99.699997,99.699997,5044984,FEDERALBNK.NS,100.599998,-0.89
2022-01-14,2626.000000,2639.000000,2590.050049,2597.000000,2597.000000,588141,TITAN.NS,2619.250000,-0.85
2022-01-14,2590.000000,2594.800049,2556.500000,2575.949951,2575.949951,84757,HEROMOTOCO.NS,2593.600098,-0.68
2022-01-14,1213.000000,1226.300049,1206.099976,1216.150024,1216.150024,2974662,TATASTEEL.NS,1221.150024,-0.41
2022-01-14,509.000000,515.400024,505.649994,510.350006,510.350006,6407847,TATAMOTORS.NS,511.950012,-0.31
2022-01-14,113.199997,115.250000,112.599998,113.349998,113.349998,10759054,NATIONALUM.NS,113.699997,-0.31
2022-01-14,325.000000,326.700012,320.600006,324.850006,324.850006,1355250,ZEEL.NS,325.450012,-0.18
2022-01-14,7775.000000,7846.100098,7728.500000,7800.000000,7800.000000,226159,BAJFINANCE.NS,7808.350098,-0.11
2022-01-14,200.000000,205.600006,199.000000,202.000000,202.000000,130261,MHRIL.NS,202.000000,0.00
2022-01-14,2535.000000,2567.300049,2525.850098,2535.500000,2535.500000,7214265,RELIANCE.NS,2535.300049,0.01
2022-01-14,199.850006,199.850006,195.500000,196.380005,196.380005,1245182,NIFTYBEES.NS,196.199997,0.09
2022-01-14,3877.850098,3918.000000,3860.050049,3905.500000,3905.500000,1065540,TCS.NS,3897.899902,0.19
2022-01-14,1530.000000,1541.199951,1519.000000,1532.000000,1532.000000,2383547,HDFCBANK.NS,1528.000000,0.26
2022-01-14,107.699997,108.849998,107.250000,108.349998,108.349998,12327694,SAIL.NS,108.050003,0.28
2022-01-14,668.000000,674.849976,666.200012,672.700012,672.700012,457514,HDFCLIFE.NS,670.349976,0.35
2022-01-14,264.799988,268.250000,260.750000,267.100006,267.100006,4987446,IEX.NS,265.950012,0.43
2022-01-14,1882.000000,1905.050049,1881.000000,1905.050049,1905.050049,2847726,INFY.NS,1896.800049,0.43
2022-01-14,243.699997,248.500000,242.500000,246.550003,246.550003,21852911,TATAPOWER.NS,245.300003,0.51
2022-01-14,224.899994,227.649994,223.500000,226.649994,226.649994,3759243,CANBK.NS,225.350006,0.58
2022-01-14,88.599998,89.199997,87.699997,88.800003,88.800003,358688,3IINFOLTD.NS,88.250000,0.62
2022-01-14,4590.000000,4623.000000,4559.000000,4622.000000,4622.000000,120378,DIVISLAB.NS,4590.049805,0.70
2022-01-14,1326.900024,1343.500000,1313.250000,1339.650024,1339.650024,277799,HAVELLS.NS,1326.900024,0.96
2022-01-14,4266.000000,4344.450195,4256.149902,4305.250000,4305.250000,336678,DMART.NS,4254.600098,1.19
2022-01-14,725.099976,742.000000,721.549988,735.549988,735.549988,80121,PARAS.NS,725.099976,1.44
2022-01-14,168.000000,174.250000,167.649994,171.600006,171.600006,5517319,IBREALEST.NS,169.100006,1.48
2022-01-14,90.000000,92.400002,90.000000,90.500000,90.500000,1474302,KELLTONTEC.NS,88.349998,2.43
2022-01-14,863.900024,904.500000,856.700012,894.299988,894.299988,7103512,IRCTC.NS,868.150024,3.01
2022-01-14,11.500000,12.200000,11.250000,12.200000,12.200000,103071657,SUZLON.NS,11.650000,4.72
2022-01-14,730.200012,769.000000,727.000000,765.450012,765.450012,3695136,TATACONSUM.NS,730.200012,4.83
2022-01-14,2366.899902,2384.399902,2364.949951,2384.399902,2384.399902,21649,TIPSINDLTD.NS,2162.800049,10.25

In [ ]:
# gainers
df_perform.sort_values(by = 'Change%', ascending=False)

,Open,High,Low,Close,Adj Close,Volume,Stock,Prev_Close,Change%
Date,,,,,,,,,
2022-01-14,2366.899902,2384.399902,2364.949951,2384.399902,2384.399902,21649,TIPSINDLTD.NS,2162.800049,10.25
2022-01-14,730.200012,769.000000,727.000000,765.450012,765.450012,3695136,TATACONSUM.NS,730.200012,4.83
2022-01-14,11.500000,12.200000,11.250000,12.200000,12.200000,103071657,SUZLON.NS,11.650000,4.72
2022-01-14,863.900024,904.500000,856.700012,894.299988,894.299988,7103512,IRCTC.NS,868.150024,3.01
2022-01-14,90.000000,92.400002,90.000000,90.500000,90.500000,1474302,KELLTONTEC.NS,88.349998,2.43
2022-01-14,168.000000,174.250000,167.649994,171.600006,171.600006,5517319,IBREALEST.NS,169.100006,1.48
2022-01-14,725.099976,742.000000,721.549988,735.549988,735.549988,80121,PARAS.NS,725.099976,1.44
2022-01-14,4266.000000,4344.450195,4256.149902,4305.250000,4305.250000,336678,DMART.NS,4254.600098,1.19
2022-01-14,1326.900024,1343.500000,1313.250000,1339.650024,1339.650024,277799,HAVELLS.NS,1326.900024,0.96
2022-01-14,4590.000000,4623.000000,4559.000000,4622.000000,4622.000000,120378,DIVISLAB.NS,4590.049805,0.70
2022-01-14,88.599998,89.199997,87.699997,88.800003,88.800003,358688,3IINFOLTD.NS,88.250000,0.62
2022-01-14,224.899994,227.649994,223.500000,226.649994,226.649994,3759243,CANBK.NS,225.350006,0.58
2022-01-14,243.699997,248.500000,242.500000,246.550003,246.550003,21852911,TATAPOWER.NS,245.300003,0.51
2022-01-14,1882.000000,1905.050049,1881.000000,1905.050049,1905.050049,2847726,INFY.NS,1896.800049,0.43
2022-01-14,264.799988,268.250000,260.750000,267.100006,267.100006,4987446,IEX.NS,265.950012,0.43
2022-01-14,668.000000,674.849976,666.200012,672.700012,672.700012,457514,HDFCLIFE.NS,670.349976,0.35
2022-01-14,107.699997,108.849998,107.250000,108.349998,108.349998,12327694,SAIL.NS,108.050003,0.28
2022-01-14,1530.000000,1541.199951,1519.000000,1532.000000,1532.000000,2383547,HDFCBANK.NS,1528.000000,0.26
2022-01-14,3877.850098,3918.000000,3860.050049,3905.500000,3905.500000,1065540,TCS.NS,3897.899902,0.19
2022-01-14,199.850006,199.850006,195.500000,196.380005,196.380005,1245182,NIFTYBEES.NS,196.199997,0.09
2022-01-14,2535.000000,2567.300049,2525.850098,2535.500000,2535.500000,7214265,RELIANCE.NS,2535.300049,0.01
2022-01-14,200.000000,205.600006,199.000000,202.000000,202.000000,130261,MHRIL.NS,202.000000,0.00
2022-01-14,7775.000000,7846.100098,7728.500000,7800.000000,7800.000000,226159,BAJFINANCE.NS,7808.350098,-0.11
2022-01-14,325.000000,326.700012,320.600006,324.850006,324.850006,1355250,ZEEL.NS,325.450012,-0.18
2022-01-14,113.199997,115.250000,112.599998,113.349998,113.349998,10759054,NATIONALUM.NS,113.699997,-0.31
2022-01-14,509.000000,515.400024,505.649994,510.350006,510.350006,6407847,TATAMOTORS.NS,511.950012,-0.31
2022-01-14,1213.000000,1226.300049,1206.099976,1216.150024,1216.150024,2974662,TATASTEEL.NS,1221.150024,-0.41
2022-01-14,2590.000000,2594.800049,2556.500000,2575.949951,2575.949951,84757,HEROMOTOCO.NS,2593.600098,-0.68
2022-01-14,2626.000000,2639.000000,2590.050049,2597.000000,2597.000000,588141,TITAN.NS,2619.250000,-0.85
2022-01-14,100.449997,101.000000,99.000000,99.699997,99.699997,5044984,FEDERALBNK.NS,100.599998,-0.89
2022-01-14,783.000000,784.849976,773.900024,774.799988,774.799988,86535,BERGEPAINT.NS,781.950012,-0.91
2022-01-14,729.950012,730.900024,724.000000,724.750000,724.750000,1874921,BHARTIARTL.NS,731.799988,-0.96
2022-01-14,959.000000,959.000000,946.900024,949.299988,949.299988,32006,MOTILALOFS.NS,958.700012,-0.98
2022-01-14,3782.000000,3782.149902,3720.000000,3721.850098,3721.850098,12506,ALKYLAMINE.NS,3758.750000,-0.98
2022-01-14,2420.000000,2421.000000,2383.199951,2386.000000,2386.000000,464289,HINDUNILVR.NS,2414.199951,-1.17
2022-01-14,5570.000000,5570.000000,5499.950195,5517.149902,5517.149902,82632,NAUKRI.NS,5590.799805,-1.32
2022-01-14,821.000000,822.000000,813.000000,813.000000,813.000000,2715408,ICICIBANK.NS,824.700012,-1.42
2022-01-14,1320.000000,1320.949951,1293.000000,1302.900024,1302.900024,2065300,HCLTECH.NS,1334.250000,-2.35
2022-01-14,919.099976,926.650024,913.250000,916.700012,916.700012,1096633,INDUSINDBK.NS,941.549988,-2.64
2022-01-14,3462.000000,3462.000000,3356.199951,3362.199951,3362.199951,529019,ASIANPAINT.NS,3456.250000,-2.72
2022-01-14,734.799988,735.950012,716.049988,717.950012,717.950012,8815753,AXISBANK.NS,740.700012,-3.07
2022-01-14,4630.000000,4675.000000,4477.350098,4507.600098,4507.600098,1391541,MINDTREE.NS,4744.100098,-4.99

In [ ]:
d = 365*5
start_date = (datetime.date.today() + datetime.timedelta(days=-d)).strftime('%Y-%m-%d')
end_date = (datetime.date.today() + datetime.timedelta(days=0)).strftime('%Y-%m-%d')

df_perform = pd.DataFrame()

for stock_id in stock_ids:
    stock_id = stock_id.upper() + '.NS'


    df_stock = pd.DataFrame(web.DataReader(tickers = stock_id, data_source='yahoo', start = start_date, end = end_date))

    CMP = df_stock['Close'].values[-1]
    D1 = round((df_stock['Close'].values[-1] - df_stock['Close'].shift(1).values[-1])*100/df_stock['Close'].shift(1).values[-1],2)
    W1 = round((df_stock['Close'].values[-1] - df_stock['Close'].shift(5).values[-1])*100/df_stock['Close'].shift(5).values[-1],2)
    M1 = round((df_stock['Close'].values[-1] - df_stock['Close'].shift(20).values[-1])*100/df_stock['Close'].shift(20).values[-1],2)
    M3 = round((df_stock['Close'].values[-1] - df_stock['Close'].shift(60).values[-1])*100/df_stock['Close'].shift(60).values[-1],2)
    M6 = round((df_stock['Close'].values[-1] - df_stock['Close'].shift(120).values[-1])*100/df_stock['Close'].shift(120).values[-1],2)
    Y1 = round((df_stock['Close'].values[-1] - df_stock['Close'].shift(240).values[-1])*100/df_stock['Close'].shift(240).values[-1],2)
    Y2 = round(((df_stock['Close'].values[-1]/df_stock['Close'].shift(240*2).values[-1])**.5 - 1)*100,2)
    Y3 = round(((df_stock['Close'].values[-1]/df_stock['Close'].shift(240*3).values[-1])**.33 - 1)*100,2)
    Y5 = round(((df_stock['Close'].values[-1]/df_stock['Close'].shift(240*5).values[-1])**.2 - 1)*100,2)
    
    
    tmp = {'Stock':[stock_id],
           'CMP': CMP,
           '1D%' : [D1],
           '1W%' : [W1],
           '1M%' : [M1],
           '3M%' : [M3],
           '6M%' : [M6],
           '1Y%' : [Y1],
           '2Y%' : [Y2],
           '3Y%' : [Y3],
           '5Y%' : [Y5]
           }

    tmp = pd.DataFrame(tmp)
    
    df_perform = df_perform.append(tmp)

df_perform

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

,Stock,CMP,1D%,1W%,1M%,3M%,6M%,1Y%,2Y%,3Y%,5Y%
0,3IINFOLTD.NS,88.250000,1.55,-1.89,-20.39,9.63,-0.84,129.22,110.06,34.43,NaN
0,ALKYLAMINE.NS,3758.750000,0.76,1.10,18.53,-4.47,-2.39,97.03,154.07,133.82,90.99
0,ASIANPAINT.NS,3456.250000,-2.47,-1.66,4.78,8.56,11.25,37.48,36.36,33.13,27.55
0,DMART.NS,4254.600098,-0.50,-9.59,-10.28,-10.52,25.23,49.97,36.39,42.90,NaN
0,AXISBANK.NS,740.700012,-0.82,1.42,4.38,-7.60,-0.81,12.50,-0.50,1.61,7.67
0,BAJFINANCE.NS,7808.350098,0.44,0.78,11.09,0.89,26.03,59.07,29.52,43.35,49.31
0,BERGEPAINT.NS,781.950012,-0.88,0.17,2.78,-5.07,-8.62,4.48,17.04,36.35,28.42
0,BHARTIARTL.NS,731.799988,0.22,3.01,7.40,7.44,33.86,26.01,16.47,36.38,17.16
0,CANBK.NS,225.350006,1.17,6.05,6.20,18.17,55.52,68.61,8.91,0.71,-4.85
0,DIVISLAB.NS,4590.049805,2.16,2.25,-0.25,-11.60,-5.23,28.61,48.34,40.50,43.47
0,FEDERALBNK.NS,100.599998,2.13,11.72,13.54,8.35,19.41,41.19,5.00,6.64,3.51
0,HAVELLS.NS,1326.900024,-2.14,-4.28,-2.51,-6.81,15.25,18.22,45.13,23.01,25.67
0,HCLTECH.NS,1334.250000,-1.32,3.84,15.05,8.29,36.34,40.82,48.17,35.67,25.49
0,HDFCBANK.NS,1528.000000,-1.84,-0.76,1.86,-9.52,5.47,4.45,10.91,12.66,17.13
0,HDFCLIFE.NS,670.349976,-0.43,3.62,0.13,-4.62,1.25,-1.48,6.08,23.53,NaN
0,HEROMOTOCO.NS,2593.600098,0.12,3.91,4.96,-9.82,-8.62,-25.36,3.03,-2.49,-4.73
0,HINDUNILVR.NS,2414.199951,0.04,0.95,4.53,-5.21,1.52,0.61,5.72,10.28,22.59
0,ICICIBANK.NS,824.700012,0.12,5.05,11.27,10.34,25.73,53.28,23.99,33.41,26.87
0,IBREALEST.NS,169.100006,-2.65,6.15,0.03,4.29,3.52,118.62,36.09,35.70,15.92
0,IEX.NS,265.950012,2.39,1.86,0.02,-5.62,79.01,243.83,110.77,67.27,NaN
0,IRCTC.NS,868.150024,0.80,2.95,1.88,-20.42,83.53,204.35,69.35,NaN,NaN
0,INDUSINDBK.NS,941.549988,2.57,4.16,0.32,-22.80,-4.08,5.40,-16.00,-14.45,-6.53
0,NAUKRI.NS,5590.799805,-0.75,0.35,1.43,-19.34,6.99,12.13,34.77,50.41,46.59
0,INFY.NS,1896.800049,1.03,4.35,7.07,4.10,19.28,43.14,56.21,35.80,30.05
0,KELLTONTEC.NS,88.349998,3.94,26.12,46.52,74.09,43.43,16.63,132.10,29.62,4.24
0,MHRIL.NS,202.000000,-0.54,7.50,-2.67,-18.71,-2.31,36.39,15.04,16.40,1.16
0,MINDTREE.NS,4744.100098,2.33,2.87,3.33,-0.07,71.96,172.52,126.86,73.05,58.20
0,MOTILALOFS.NS,958.700012,3.27,4.45,-2.15,6.36,-11.21,55.29,8.88,18.34,6.44
0,NATIONALUM.NS,113.699997,2.16,8.39,12.80,-0.31,33.76,146.37,58.78,29.33,7.83
0,NIFTYBEES.NS,196.199997,0.78,1.48,5.34,-1.36,16.41,27.48,23.35,19.55,16.47
0,PARAS.NS,725.099976,-0.96,-0.19,3.22,-19.47,NaN,NaN,NaN,NaN,NaN
0,RELIANCE.NS,2535.300049,0.56,4.92,5.47,-7.19,19.55,30.62,33.61,26.46,31.44
0,SAIL.NS,108.050003,2.95,-3.83,-4.80,-12.08,-14.35,85.49,49.03,31.34,12.34
0,SUZLON.NS,11.650000,-4.90,14.78,65.25,62.94,53.29,92.56,127.55,49.42,-8.02
0,TCS.NS,3897.899902,0.98,2.38,8.83,7.26,21.19,18.43,35.07,23.59,25.54
0,TATACONSUM.NS,730.200012,-0.80,0.65,-1.36,-13.41,-4.45,27.30,35.67,56.88,38.60
0,TATAMOTORS.NS,511.950012,0.93,4.73,4.07,6.24,69.21,83.40,71.73,49.36,1.83
0,TATAPOWER.NS,245.300003,3.18,7.38,10.55,6.77,98.30,209.53,105.65,53.99,24.20
0,TATASTEEL.NS,1221.150024,6.45,4.98,5.89,-10.66,-4.07,87.31,61.02,35.40,21.60
0,TIPSINDLTD.NS,2162.800049,-3.51,2.08,28.20,54.86,81.98,473.53,331.70,226.23,104.11
0,TITAN.NS,2619.250000,0.24,0.90,11.11,5.41,53.92,74.63,43.33,34.53,42.90
0,ZEEL.NS,325.450012,-0.14,0.28,-11.61,5.26,58.87,45.49,14.15,-7.69,-8.47

In [ ]:
df_perform.sort_values(by = '3M%', ascending = False)

,Stock,CMP,1D%,1W%,1M%,3M%,6M%,1Y%,2Y%,3Y%,5Y%
0,KELLTONTEC.NS,88.349998,3.94,26.12,46.52,74.09,43.43,16.63,132.10,29.62,4.24
0,SUZLON.NS,11.650000,-4.90,14.78,65.25,62.94,53.29,92.56,127.55,49.42,-8.02
0,TIPSINDLTD.NS,2162.800049,-3.51,2.08,28.20,54.86,81.98,473.53,331.70,226.23,104.11
0,CANBK.NS,225.350006,1.17,6.05,6.20,18.17,55.52,68.61,8.91,0.71,-4.85
0,ICICIBANK.NS,824.700012,0.12,5.05,11.27,10.34,25.73,53.28,23.99,33.41,26.87
0,3IINFOLTD.NS,88.250000,1.55,-1.89,-20.39,9.63,-0.84,129.22,110.06,34.43,NaN
0,ASIANPAINT.NS,3456.250000,-2.47,-1.66,4.78,8.56,11.25,37.48,36.36,33.13,27.55
0,FEDERALBNK.NS,100.599998,2.13,11.72,13.54,8.35,19.41,41.19,5.00,6.64,3.51
0,HCLTECH.NS,1334.250000,-1.32,3.84,15.05,8.29,36.34,40.82,48.17,35.67,25.49
0,BHARTIARTL.NS,731.799988,0.22,3.01,7.40,7.44,33.86,26.01,16.47,36.38,17.16
0,TCS.NS,3897.899902,0.98,2.38,8.83,7.26,21.19,18.43,35.07,23.59,25.54
0,TATAPOWER.NS,245.300003,3.18,7.38,10.55,6.77,98.30,209.53,105.65,53.99,24.20
0,MOTILALOFS.NS,958.700012,3.27,4.45,-2.15,6.36,-11.21,55.29,8.88,18.34,6.44
0,TATAMOTORS.NS,511.950012,0.93,4.73,4.07,6.24,69.21,83.40,71.73,49.36,1.83
0,TITAN.NS,2619.250000,0.24,0.90,11.11,5.41,53.92,74.63,43.33,34.53,42.90
0,ZEEL.NS,325.450012,-0.14,0.28,-11.61,5.26,58.87,45.49,14.15,-7.69,-8.47
0,IBREALEST.NS,169.100006,-2.65,6.15,0.03,4.29,3.52,118.62,36.09,35.70,15.92
0,INFY.NS,1896.800049,1.03,4.35,7.07,4.10,19.28,43.14,56.21,35.80,30.05
0,BAJFINANCE.NS,7808.350098,0.44,0.78,11.09,0.89,26.03,59.07,29.52,43.35,49.31
0,MINDTREE.NS,4744.100098,2.33,2.87,3.33,-0.07,71.96,172.52,126.86,73.05,58.20
0,NATIONALUM.NS,113.699997,2.16,8.39,12.80,-0.31,33.76,146.37,58.78,29.33,7.83
0,NIFTYBEES.NS,196.199997,0.78,1.48,5.34,-1.36,16.41,27.48,23.35,19.55,16.47
0,ALKYLAMINE.NS,3758.750000,0.76,1.10,18.53,-4.47,-2.39,97.03,154.07,133.82,90.99
0,HDFCLIFE.NS,670.349976,-0.43,3.62,0.13,-4.62,1.25,-1.48,6.08,23.53,NaN
0,BERGEPAINT.NS,781.950012,-0.88,0.17,2.78,-5.07,-8.62,4.48,17.04,36.35,28.42
0,HINDUNILVR.NS,2414.199951,0.04,0.95,4.53,-5.21,1.52,0.61,5.72,10.28,22.59
0,IEX.NS,265.950012,2.39,1.86,0.02,-5.62,79.01,243.83,110.77,67.27,NaN
0,HAVELLS.NS,1326.900024,-2.14,-4.28,-2.51,-6.81,15.25,18.22,45.13,23.01,25.67
0,RELIANCE.NS,2535.300049,0.56,4.92,5.47,-7.19,19.55,30.62,33.61,26.46,31.44
0,AXISBANK.NS,740.700012,-0.82,1.42,4.38,-7.60,-0.81,12.50,-0.50,1.61,7.67
0,HDFCBANK.NS,1528.000000,-1.84,-0.76,1.86,-9.52,5.47,4.45,10.91,12.66,17.13
0,HEROMOTOCO.NS,2593.600098,0.12,3.91,4.96,-9.82,-8.62,-25.36,3.03,-2.49,-4.73
0,DMART.NS,4254.600098,-0.50,-9.59,-10.28,-10.52,25.23,49.97,36.39,42.90,NaN
0,TATASTEEL.NS,1221.150024,6.45,4.98,5.89,-10.66,-4.07,87.31,61.02,35.40,21.60
0,DIVISLAB.NS,4590.049805,2.16,2.25,-0.25,-11.60,-5.23,28.61,48.34,40.50,43.47
0,SAIL.NS,108.050003,2.95,-3.83,-4.80,-12.08,-14.35,85.49,49.03,31.34,12.34
0,TATACONSUM.NS,730.200012,-0.80,0.65,-1.36,-13.41,-4.45,27.30,35.67,56.88,38.60
0,MHRIL.NS,202.000000,-0.54,7.50,-2.67,-18.71,-2.31,36.39,15.04,16.40,1.16
0,NAUKRI.NS,5590.799805,-0.75,0.35,1.43,-19.34,6.99,12.13,34.77,50.41,46.59
0,PARAS.NS,725.099976,-0.96,-0.19,3.22,-19.47,NaN,NaN,NaN,NaN,NaN
0,IRCTC.NS,868.150024,0.80,2.95,1.88,-20.42,83.53,204.35,69.35,NaN,NaN
0,INDUSINDBK.NS,941.549988,2.57,4.16,0.32,-22.80,-4.08,5.40,-16.00,-14.45,-6.53

In [ ]:
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import pandas_datareader.data as web
import yfinance as yfin
yfin.pdr_override()

start_date = (datetime.date.today() + datetime.timedelta(days=-60)).strftime('%Y-%m-%d')
end_date = (datetime.date.today() + datetime.timedelta(days=0)).strftime('%Y-%m-%d')

df_perform = pd.DataFrame()

for stock_id in stock_ids:
    stock_id = stock_id.upper() + '.NS'
    tmp = pd.DataFrame(web.DataReader(tickers = stock_id, data_source='yahoo', start = start_date, end = end_date))
    tmp['Stock'] = stock_id
    tmp['Prev_Close'] = tmp['Close'].shift(1)
    tmp['Change%'] = round((tmp['Close'] - tmp['Prev_Close'])*100/tmp['Prev_Close'],2)
    df_perform = df_perform.append(tmp)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

In [ ]:
# losers
df_perform.sort_values(by = 'Change%').head(20)

,Open,High,Low,Close,Adj Close,Volume,Stock,Prev_Close,Change%
Date,,,,,,,,,
2021-11-26,95.699997,95.699997,87.400002,88.099998,88.099998,58612326,NATIONALUM.NS,96.900002,-9.08
2022-01-12,95.900002,96.199997,84.800003,85.000000,85.000000,6011291,KELLTONTEC.NS,92.650002,-8.26
2021-12-17,169.000000,169.449997,155.250000,157.149994,157.149994,16738339,IBREALEST.NS,169.050003,-7.04
2021-12-17,365.500000,365.700012,338.649994,342.350006,342.350006,29550773,ZEEL.NS,368.200012,-7.02
2021-11-26,226.500000,226.500000,211.100006,213.399994,213.399994,562174,MHRIL.NS,229.500000,-7.02
2021-12-20,250.000000,251.000000,235.399994,238.600006,238.600006,23427782,IEX.NS,256.100006,-6.83
2021-11-26,486.000000,486.750000,458.000000,460.200012,460.200012,51787989,TATAMOTORS.NS,492.750000,-6.61
2021-11-22,174.699997,177.649994,159.350006,162.100006,162.100006,16600806,IBREALEST.NS,173.399994,-6.52
2021-11-22,6521.000000,6561.450195,5959.200195,6071.899902,6071.899902,588081,NAUKRI.NS,6485.899902,-6.38
2021-11-26,238.000000,240.300003,225.750000,227.350006,227.350006,80108784,TATAPOWER.NS,242.800003,-6.36
2021-12-15,280.100006,281.000000,260.500000,261.600006,261.600006,40586645,IEX.NS,278.950012,-6.22
2021-12-20,4549.000000,4559.000000,4249.950195,4304.700195,4304.700195,972608,MINDTREE.NS,4587.700195,-6.17
2021-11-26,173.000000,175.899994,165.500000,166.649994,166.649994,17965587,IBREALEST.NS,177.300003,-6.01
2021-11-22,239.500000,239.500000,218.050003,222.300003,222.300003,355610,MHRIL.NS,236.500000,-6.00
2021-11-26,951.000000,956.950012,898.000000,901.799988,901.799988,6746021,INDUSINDBK.NS,959.299988,-5.99
2021-11-26,4709.000000,4710.000000,4426.850098,4454.750000,4454.750000,1287611,MINDTREE.NS,4737.299805,-5.96
2021-12-20,155.500000,155.500000,143.600006,147.800003,147.800003,15295099,IBREALEST.NS,157.149994,-5.95
2021-11-26,212.899994,213.899994,201.600006,202.649994,202.649994,13422935,CANBK.NS,215.050003,-5.77
2021-11-29,786.000000,801.000000,750.549988,775.799988,775.799988,13888743,IRCTC.NS,823.049988,-5.74
2021-11-26,108.550003,109.199997,103.099998,103.650002,103.650002,56238864,SAIL.NS,109.949997,-5.73

In [ ]:
# gainers
df_perform.sort_values(by = 'Change%', ascending=False).head(20)

,Open,High,Low,Close,Adj Close,Volume,Stock,Prev_Close,Change%
Date,,,,,,,,,
2022-01-11,83.599998,96.650002,83.500000,92.650002,92.650002,13877644,KELLTONTEC.NS,81.400002,13.82
2022-01-10,75.199997,85.199997,74.800003,81.400002,81.400002,9981491,KELLTONTEC.NS,73.300003,11.05
2021-12-09,53.500000,59.599998,53.299999,58.700001,58.700001,4087811,KELLTONTEC.NS,53.650002,9.41
2021-12-10,271.000000,303.799988,269.850006,295.250000,295.250000,67352246,IEX.NS,269.850006,9.41
2021-12-06,50.400002,54.799999,49.299999,52.750000,52.750000,2473992,KELLTONTEC.NS,48.299999,9.21
2022-01-12,189.000000,209.699997,189.000000,203.100006,203.100006,3426740,MHRIL.NS,187.850006,8.12
2021-11-23,161.000000,176.399994,160.800003,174.050003,174.050003,17366983,IBREALEST.NS,162.100006,7.37
2021-12-07,92.750000,97.250000,92.449997,96.599998,96.599998,65949099,NATIONALUM.NS,90.199997,7.10
2021-11-24,317.450012,337.799988,314.299988,334.399994,334.399994,40329091,ZEEL.NS,312.399994,7.04
2021-12-27,651.000000,754.599976,651.000000,732.900024,732.900024,461883,PARAS.NS,686.000000,6.84
2021-12-21,151.199997,159.500000,151.199997,157.800003,157.800003,13149711,IBREALEST.NS,147.800003,6.77
2021-12-31,3340.000000,3566.000000,3335.000000,3547.699951,3547.699951,226865,ALKYLAMINE.NS,3326.899902,6.64
2022-01-13,1154.000000,1225.500000,1152.150024,1221.150024,1221.150024,15723116,TATASTEEL.NS,1147.199951,6.45
2021-11-25,2373.000000,2502.000000,2357.149902,2492.949951,2492.949951,19568487,RELIANCE.NS,2351.399902,6.02
2022-01-03,3576.300049,3778.750000,3575.000000,3759.350098,3759.350098,281570,ALKYLAMINE.NS,3547.699951,5.97
2021-12-10,170.000000,181.699997,168.699997,179.100006,179.100006,22477130,IBREALEST.NS,169.199997,5.85
2021-12-01,891.000000,938.750000,890.150024,933.650024,933.650024,14626216,INDUSINDBK.NS,883.000000,5.74
2022-01-07,106.550003,111.449997,105.250000,110.699997,110.699997,47566917,NATIONALUM.NS,104.900002,5.53
2022-01-06,65.699997,71.000000,64.750000,70.050003,70.050003,4219369,KELLTONTEC.NS,66.449997,5.42
2021-12-21,94.849998,100.349998,94.699997,98.449997,98.449997,34863302,NATIONALUM.NS,93.400002,5.41

In [ ]:
df_perform[df_perform['Stock'] == 'RELIANCE.NS']

,Open,High,Low,Close,Adj Close,Volume,Stock,Prev_Close,Change%
Date,,,,,,,,,
2021-11-15,2600.000000,2602.199951,2570.000000,2577.800049,2577.800049,2216708,RELIANCE.NS,NaN,NaN
2021-11-16,2572.050049,2575.000000,2495.000000,2517.899902,2517.899902,5232292,RELIANCE.NS,2577.800049,-2.32
2021-11-17,2498.949951,2498.949951,2461.000000,2464.000000,2464.000000,4708235,RELIANCE.NS,2517.899902,-2.14
2021-11-18,2460.000000,2489.000000,2450.050049,2473.300049,2473.300049,3925345,RELIANCE.NS,2464.000000,0.38
2021-11-22,2436.100098,2449.000000,2351.000000,2363.750000,2363.750000,11133364,RELIANCE.NS,2473.300049,-4.43
2021-11-23,2333.050049,2401.250000,2309.000000,2385.850098,2385.850098,11688406,RELIANCE.NS,2363.750000,0.93
2021-11-24,2380.000000,2409.899902,2343.550049,2351.399902,2351.399902,7762564,RELIANCE.NS,2385.850098,-1.44
2021-11-25,2373.000000,2502.000000,2357.149902,2492.949951,2492.949951,19568487,RELIANCE.NS,2351.399902,6.02
2021-11-26,2467.800049,2477.600098,2401.500000,2412.600098,2412.600098,7274686,RELIANCE.NS,2492.949951,-3.22
2021-11-29,2439.100098,2500.000000,2399.100098,2441.500000,2441.500000,11226147,RELIANCE.NS,2412.600098,1.20
2021-11-30,2468.000000,2475.899902,2388.850098,2405.399902,2405.399902,14847511,RELIANCE.NS,2441.500000,-1.48
2021-12-01,2433.000000,2474.000000,2425.100098,2467.000000,2467.000000,4663276,RELIANCE.NS,2405.399902,2.56
2021-12-02,2469.699951,2496.199951,2461.600098,2482.850098,2482.850098,5870468,RELIANCE.NS,2467.000000,0.64
2021-12-03,2498.399902,2498.500000,2400.000000,2408.250000,2408.250000,8871172,RELIANCE.NS,2482.850098,-3.00
2021-12-06,2416.000000,2425.000000,2357.149902,2362.600098,2362.600098,4768334,RELIANCE.NS,2408.250000,-1.90
2021-12-07,2376.149902,2404.000000,2360.000000,2381.850098,2381.850098,5185007,RELIANCE.NS,2362.600098,0.81
2021-12-08,2424.100098,2431.800049,2406.300049,2418.100098,2418.100098,4035437,RELIANCE.NS,2381.850098,1.52
2021-12-09,2435.000000,2474.899902,2425.000000,2456.449951,2456.449951,6098050,RELIANCE.NS,2418.100098,1.59
2021-12-10,2440.250000,2466.000000,2430.350098,2458.949951,2458.949951,3860176,RELIANCE.NS,2456.449951,0.10
2021-12-13,2473.500000,2474.100098,2404.000000,2409.649902,2409.649902,5954148,RELIANCE.NS,2458.949951,-2.00
2021-12-14,2380.000000,2406.000000,2373.399902,2380.149902,2380.149902,5995586,RELIANCE.NS,2409.649902,-1.22
2021-12-15,2384.000000,2405.000000,2361.100098,2373.199951,2373.199951,4322855,RELIANCE.NS,2380.149902,-0.29
2021-12-16,2405.699951,2415.500000,2368.649902,2403.899902,2403.899902,4504829,RELIANCE.NS,2373.199951,1.29
2021-12-17,2398.050049,2408.000000,2320.000000,2340.449951,2340.449951,9714489,RELIANCE.NS,2403.899902,-2.64
2021-12-20,2317.850098,2317.850098,2247.100098,2277.350098,2277.350098,6611376,RELIANCE.NS,2340.449951,-2.70
2021-12-21,2311.350098,2346.000000,2292.199951,2311.250000,2311.250000,5924071,RELIANCE.NS,2277.350098,1.49
2021-12-22,2324.899902,2371.899902,2322.000000,2366.100098,2366.100098,8149415,RELIANCE.NS,2311.250000,2.37
2021-12-23,2374.000000,2380.000000,2358.050049,2365.250000,2365.250000,4186912,RELIANCE.NS,2366.100098,-0.04
2021-12-24,2370.000000,2392.000000,2337.550049,2372.800049,2372.800049,3639616,RELIANCE.NS,2365.250000,0.32
2021-12-27,2361.550049,2378.000000,2348.100098,2370.250000,2370.250000,1853948,RELIANCE.NS,2372.800049,-0.11
2021-12-28,2375.600098,2404.850098,2373.050049,2398.399902,2398.399902,2941883,RELIANCE.NS,2370.250000,1.19
2021-12-29,2391.000000,2419.000000,2382.100098,2402.500000,2402.500000,7118779,RELIANCE.NS,2398.399902,0.17
2021-12-30,2400.000000,2404.949951,2345.600098,2359.100098,2359.100098,13537254,RELIANCE.NS,2402.500000,-1.81
2021-12-31,2373.000000,2383.899902,2360.000000,2368.149902,2368.149902,4373768,RELIANCE.NS,2359.100098,0.38
2022-01-03,2365.000000,2407.949951,2363.550049,2403.850098,2403.850098,2502073,RELIANCE.NS,2368.149902,1.51
2022-01-04,2415.899902,2461.000000,2404.000000,2458.100098,2458.100098,5006225,RELIANCE.NS,2403.850098,2.26
2022-01-05,2462.000000,2477.000000,2432.949951,2469.600098,2469.600098,5373618,RELIANCE.NS,2458.100098,0.47
2022-01-06,2451.199951,2454.000000,2409.000000,2416.500000,2416.500000,6667483,RELIANCE.NS,2469.600098,-2.15
2022-01-07,2430.949951,2458.050049,2411.550049,2436.000000,2436.000000,6051239,RELIANCE.NS,2416.500000,0.81
2022-01-10,2452.000000,2457.000000,2416.050049,2438.000000,2438.000000,4267365,RELIANCE.NS,2436.000000,0.08
2022-01-11,2436.000000,2474.949951,2435.000000,2455.550049,2455.550049,7478681,RELIANCE.NS,2438.000000,0.72
2022-01-12,2471.300049,2524.949951,2465.000000,2521.100098,2521.100098,6830402,RELIANCE.NS,2455.550049,2.67
2022-01-13,2521.250000,2541.000000,2508.399902,2535.300049,2535.300049,5471871,RELIANCE.NS,2521.100098,0.56

In [ ]:
stock_id = '^NSEI'
nifty = pd.DataFrame(web.DataReader(tickers = stock_id, data_source='yahoo', start = '2020-01-01', end = '2021-11-30'))
nifty['Stock'] = stock_id
nifty['Prev_Close'] = nifty['Close'].shift(1)
nifty['Change%'] = round((nifty['Close'] - nifty['Prev_Close'])*100/nifty['Prev_Close'],2)

nifty

[*********************100%***********************]  1 of 1 completed

,Open,High,Low,Close,Adj Close,Volume,Stock,Prev_Close,Change%
Date,,,,,,,,,
2020-01-01,12202.150391,12222.200195,12165.299805,12182.500000,12182.500000,304100,^NSEI,NaN,NaN
2020-01-02,12198.549805,12289.900391,12195.250000,12282.200195,12282.200195,407700,^NSEI,12182.500000,0.82
2020-01-03,12261.099609,12265.599609,12191.349609,12226.650391,12226.650391,428800,^NSEI,12282.200195,-0.45
2020-01-06,12170.599609,12179.099609,11974.200195,11993.049805,11993.049805,396500,^NSEI,12226.650391,-1.91
2020-01-07,12079.099609,12152.150391,12005.349609,12052.950195,12052.950195,447800,^NSEI,11993.049805,0.50
...,...,...,...,...,...,...,...,...,...
2021-11-23,17281.750000,17553.699219,17216.099609,17503.349609,17503.349609,308800,^NSEI,17416.550781,0.50
2021-11-24,17550.050781,17600.599609,17354.000000,17415.050781,17415.050781,298100,^NSEI,17503.349609,-0.50
2021-11-25,17417.300781,17564.349609,17351.699219,17536.250000,17536.250000,255900,^NSEI,17415.050781,0.70
2021-11-26,17338.750000,17355.400391,16985.699219,17026.449219,17026.449219,356300,^NSEI,17536.250000,-2.91
2021-11-29,17055.800781,17160.699219,16782.400391,17053.949219,17053.949219,348900,^NSEI,17026.449219,0.16

In [ ]:
nifty.sort_values(by = 'Change%', ascending=True).head(20)

,Open,High,Low,Close,Adj Close,Volume,Stock,Prev_Close,Change%
Date,,,,,,,,,
2020-03-23,7945.700195,8159.250000,7583.600098,7610.250000,7610.250000,653500,^NSEI,8745.450195,-12.98
2020-03-12,10039.950195,10040.750000,9508.000000,9590.150391,9590.150391,1343500,^NSEI,10458.400391,-8.30
2020-03-16,9587.799805,9602.200195,9165.099609,9197.400391,9197.400391,897700,^NSEI,9955.200195,-7.61
2020-05-04,9533.500000,9533.500000,9266.950195,9293.500000,9293.500000,687500,^NSEI,9859.900391,-5.74
2020-03-18,9088.450195,9127.549805,8407.049805,8468.799805,8468.799805,1516600,^NSEI,8967.049805,-5.56
2020-03-09,10742.049805,10751.549805,10294.450195,10451.450195,10451.450195,1565500,^NSEI,10989.450195,-4.90
2020-03-30,8385.950195,8576.000000,8244.000000,8281.099609,8281.099609,593300,^NSEI,8660.250000,-4.38
2020-04-01,8584.099609,8588.099609,8198.349609,8253.799805,8253.799805,506300,^NSEI,8597.750000,-4.00
2021-02-26,14888.599609,14919.450195,14467.750000,14529.150391,14529.150391,1103600,^NSEI,15097.349609,-3.76
2020-02-28,11382.000000,11384.799805,11175.049805,11201.750000,11201.750000,809900,^NSEI,11633.299805,-3.71
2021-04-12,14644.650391,14652.500000,14248.700195,14310.799805,14310.799805,650200,^NSEI,14834.849609,-3.53
2020-05-18,9158.299805,9158.299805,8806.750000,8823.250000,8823.250000,773000,^NSEI,9136.849609,-3.43
2020-12-21,13741.900391,13777.500000,13131.450195,13328.400391,13328.400391,687300,^NSEI,13760.549805,-3.14
2020-04-21,9016.950195,9044.400391,8909.400391,8981.450195,8981.450195,655100,^NSEI,9261.849609,-3.03
2020-09-24,11011.000000,11015.299805,10790.200195,10805.549805,10805.549805,706100,^NSEI,11131.849609,-2.93
2021-11-26,17338.750000,17355.400391,16985.699219,17026.449219,17026.449219,356300,^NSEI,17536.250000,-2.91
2020-05-14,9213.950195,9281.099609,9119.750000,9142.750000,9142.750000,602600,^NSEI,9383.549805,-2.57
2020-03-17,9285.400391,9403.799805,8915.599609,8967.049805,8967.049805,935600,^NSEI,9197.400391,-2.50
2020-03-06,10942.650391,11035.099609,10827.400391,10989.450195,10989.450195,1811000,^NSEI,11269.000000,-2.48
2020-10-15,12023.450195,12025.450195,11661.299805,11680.349609,11680.349609,608900,^NSEI,11971.049805,-2.43

In [ ]:
nifty.sort_values(by = 'Change%', ascending=False).head(20)

,Open,High,Low,Close,Adj Close,Volume,Stock,Prev_Close,Change%
Date,,,,,,,,,
2020-04-07,8446.299805,8819.400391,8360.950195,8792.200195,8792.200195,814200,^NSEI,8083.799805,8.76
2020-03-25,7735.149902,8376.750000,7714.750000,8317.849609,8317.849609,736900,^NSEI,7801.049805,6.62
2020-03-20,8284.450195,8883.000000,8178.200195,8745.450195,8745.450195,1071500,^NSEI,8263.450195,5.83
2021-02-01,13758.599609,14336.349609,13661.750000,14281.200195,14281.200195,870500,^NSEI,13634.599609,4.74
2020-04-09,8973.049805,9128.349609,8904.549805,9111.900391,9111.900391,742100,^NSEI,8748.750000,4.15
2020-03-26,8451.000000,8749.049805,8304.900391,8641.450195,8641.450195,865600,^NSEI,8317.849609,3.89
2020-03-31,8529.349609,8678.299805,8358.000000,8597.750000,8597.750000,712700,^NSEI,8281.099609,3.82
2020-03-13,9107.599609,10159.400391,8555.150391,9955.200195,9955.200195,1388000,^NSEI,9590.150391,3.81
2020-04-30,9753.500000,9889.049805,9731.500000,9859.900391,9859.900391,931200,^NSEI,9553.349609,3.21
2020-05-27,9082.200195,9334.000000,9004.250000,9314.950195,9314.950195,763500,^NSEI,9029.049805,3.17
2020-04-17,9323.450195,9324.000000,9091.349609,9266.750000,9266.750000,684200,^NSEI,8992.799805,3.05
2021-02-02,14481.099609,14731.700195,14469.150391,14647.849609,14647.849609,915000,^NSEI,14281.200195,2.57
2020-06-01,9726.849609,9931.599609,9706.950195,9826.150391,9826.150391,794200,^NSEI,9580.299805,2.57
2020-03-24,7848.299805,8036.950195,7511.100098,7801.049805,7801.049805,738400,^NSEI,7610.250000,2.51
2021-03-30,14628.500000,14876.299805,14617.599609,14845.099609,14845.099609,594500,^NSEI,14507.299805,2.33
2020-02-04,11786.250000,11986.150391,11783.400391,11979.650391,11979.650391,560400,^NSEI,11707.900391,2.32
2020-04-22,9026.750000,9209.750000,8946.250000,9187.299805,9187.299805,734400,^NSEI,8981.450195,2.29
2020-09-25,10910.400391,11072.599609,10854.849609,11050.250000,11050.250000,559600,^NSEI,10805.549805,2.26
2021-03-03,15064.400391,15273.150391,14995.799805,15245.599609,15245.599609,544200,^NSEI,14919.099609,2.19
2020-06-18,9863.250000,10111.200195,9845.049805,10091.650391,10091.650391,622900,^NSEI,9881.150391,2.13

In [ ]:
stock_id = '^NSEI'
nifty = pd.DataFrame(web.DataReader(tickers = stock_id, data_source='yahoo', start = '2020-03-01', end = '2021-12-10'))
nifty['Stock'] = stock_id
nifty['Prev_Close'] = nifty['Close'].shift(1)
nifty['Change%'] = round((nifty['Close'] - nifty['Prev_Close'])*100/nifty['Prev_Close'],2)

nifty

[*********************100%***********************]  1 of 1 completed

,Open,High,Low,Close,Adj Close,Volume,Stock,Prev_Close,Change%
Date,,,,,,,,,
2020-03-02,11387.349609,11433.000000,11036.250000,11132.750000,11132.750000,680800,^NSEI,NaN,NaN
2020-03-03,11217.549805,11342.250000,11152.549805,11303.299805,11303.299805,696500,^NSEI,11132.750000,1.53
2020-03-04,11351.349609,11356.599609,11082.150391,11251.000000,11251.000000,797700,^NSEI,11303.299805,-0.46
2020-03-05,11306.049805,11389.500000,11244.599609,11269.000000,11269.000000,1352500,^NSEI,11251.000000,0.16
2020-03-06,10942.650391,11035.099609,10827.400391,10989.450195,10989.450195,1811000,^NSEI,11269.000000,-2.48
...,...,...,...,...,...,...,...,...,...
2021-12-03,17424.900391,17489.800781,17180.800781,17196.699219,17196.699219,292500,^NSEI,17401.650391,-1.18
2021-12-06,17209.050781,17216.750000,16891.699219,16912.250000,16912.250000,231700,^NSEI,17196.699219,-1.65
2021-12-07,17044.099609,17251.650391,16987.750000,17176.699219,17176.699219,254100,^NSEI,16912.250000,1.56
2021-12-08,17315.250000,17484.599609,17308.949219,17469.750000,17469.750000,257800,^NSEI,17176.699219,1.71
2021-12-09,17524.400391,17543.250000,17379.599609,17516.849609,17516.849609,237200,^NSEI,17469.750000,0.27

In [ ]:
cols = ['Adj Close', 'Change%']
nifty[nifty['Change%'] < -1][cols].tail(6)['Adj Close']

Date
2021-10-28    17857.250000
2021-10-29    17671.650391
2021-11-22    17416.550781
2021-11-26    17026.449219
2021-12-03    17196.699219
2021-12-06    16912.250000
Name: Adj Close, dtype: float64

In [ ]:
stock_id = 'NIFTYBEES.NS'
nifty20 = pd.DataFrame(web.DataReader(tickers = stock_id, data_source='yahoo', start = '2020-03-01', end = '2021-12-10'))
nifty20['Stock'] = stock_id
nifty20['Prev_Close'] = nifty['Close'].shift(1)
nifty20['Change%'] = round((nifty['Close'] - nifty['Prev_Close'])*100/nifty['Prev_Close'],2)

nifty20

[*********************100%***********************]  1 of 1 completed

,Open,High,Low,Close,Adj Close,Volume,Stock,Prev_Close,Change%
Date,,,,,,,,,
2020-03-02,122.050003,122.050003,117.209999,118.389999,118.389999,2355594,NIFTYBEES.NS,NaN,NaN
2020-03-03,119.440002,121.010002,118.550003,120.400002,120.400002,1810345,NIFTYBEES.NS,11132.750000,1.53
2020-03-04,121.400002,121.400002,117.910004,119.519997,119.519997,2300345,NIFTYBEES.NS,11303.299805,-0.46
2020-03-05,142.949997,142.949997,118.599998,119.750000,119.750000,513870,NIFTYBEES.NS,11251.000000,0.16
2020-03-06,118.489998,118.489998,115.599998,117.180000,117.180000,3370046,NIFTYBEES.NS,11269.000000,-2.48
...,...,...,...,...,...,...,...,...,...
2021-12-03,192.500000,192.500000,185.750000,186.000000,186.000000,1581371,NIFTYBEES.NS,17401.650391,-1.18
2021-12-06,192.399994,192.399994,182.800003,183.009995,183.009995,2784801,NIFTYBEES.NS,17196.699219,-1.65
2021-12-07,190.000000,190.000000,180.100006,185.710007,185.710007,1224647,NIFTYBEES.NS,16912.250000,1.56
2021-12-08,191.000000,191.000000,185.710007,188.479996,188.479996,1425972,NIFTYBEES.NS,17176.699219,1.71
2021-12-09,192.500000,192.500000,187.160004,189.139999,189.139999,1108273,NIFTYBEES.NS,17469.750000,0.27

In [ ]:
cols = ['Adj Close', 'Change%']
nifty20[nifty20['Change%'] < -1][cols].tail(6)['Adj Close']

Date
2021-10-28    193.679993
2021-10-29    191.160004
2021-11-22    188.529999
2021-11-26    184.509995
2021-12-03    186.000000
2021-12-06    183.009995
Name: Adj Close, dtype: float64